"""added sission fied info

Revision ID: 00d959ff4243
Revises: ee83e1975eb6
Create Date: 2023-06-04 00:16:41.570350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00d959ff4243'
down_revision = 'ee83e1975eb6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrapper_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('last_page', sa.Integer(), nullable=True),
    sa.Column('last_scrapper_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scrapper_info')
    # ### end Alembic commands ###
