"""change

Revision ID: 9af67a26a628
Revises: 00d959ff4243
Create Date: 2023-06-04 01:09:07.857441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9af67a26a628'
down_revision = '00d959ff4243'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
