"""added relations for marks

Revision ID: 9f6165720c7a
Revises: ddc25e0d9128
Create Date: 2023-06-01 23:48:06.279338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f6165720c7a'
down_revision = 'ddc25e0d9128'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('category_id', sa.Integer(), nullable=False))
    op.add_column('models', sa.Column('mark_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'models', 'marks', ['mark_id'], ['id'])
    op.create_foreign_key(None, 'models', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'models', type_='foreignkey')
    op.drop_constraint(None, 'models', type_='foreignkey')
    op.drop_column('models', 'mark_id')
    op.drop_column('models', 'category_id')
    # ### end Alembic commands ###
