"""change fuel

Revision ID: d262a24abeac
Revises: 9af67a26a628
Create Date: 2023-06-04 02:21:22.581494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd262a24abeac'
down_revision = '9af67a26a628'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
