"""fix city of auto data

Revision ID: d4ff438d7f38
Revises: fe650a77e709
Create Date: 2023-06-04 23:01:35.071487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4ff438d7f38'
down_revision = 'fe650a77e709'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
