"""fix db

Revision ID: ee83e1975eb6
Revises: bbf35862d8dd
Create Date: 2023-06-02 19:34:38.074951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee83e1975eb6'
down_revision = 'bbf35862d8dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
