"""fix city of auto data

Revision ID: fe650a77e709
Revises: d262a24abeac
Create Date: 2023-06-04 23:00:56.059154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe650a77e709'
down_revision = 'd262a24abeac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
